TradingPlatform/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using TradingPlatform.Infrastructure.Services.Interfaces;
using TradingPlatform.Repositories;
using TradingPlatform.ViewModels;

namespace TradingPlatform.Controllers
{
    public class ItemController : Controller
    {
        public IFileService _fileService { get; set; }

        public IWebHostEnvironment _appEnvironment { get; set; }

        public IItemRepository _repository { get; set; }

        public IUserRepository _userRepository { get; set; }

        public ICategoryRepository _categoryRepository { get; set; }

        public IOrderRepository _orderRepository { get; set; }

        public IMessageService _messageService { get; set; }

        public ItemController(IFileService fileService, IWebHostEnvironment appEnvironment, IItemRepository repository, IUserRepository userRepository, ICategoryRepository categoryRepository, IOrderRepository orderRepository, IMessageService messageService)
        {
            _fileService = fileService;
            _appEnvironment = appEnvironment;
            _repository = repository;
            _userRepository = userRepository;
            _categoryRepository = categoryRepository;
            _orderRepository = orderRepository;
            _messageService = messageService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddItem()
        {
            if (User.Identity.Name != null)
            {
                var currency = _userRepository.UserCurrency(User.Identity.Name);
                ViewData["Currency"] = currency;
                ItemAddViewModel model = new ItemAddViewModel();
                model.Categories = _categoryRepository.GetAllCategoriesSelectedList();


                return View(model);
            }


            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddItem(ItemAddViewModel item)
        {
            var userName = User.Identity.Name;

            if (ModelState.IsValid)
            {
                item.UserName = userName;
                item.Status = Status.Added;

                await _repository.AddItem(item);
            }


            return View(item);
        }

        public IActionResult ViewItem(int itemId)
        {
            var item = _repository.GetItem(itemId);

            ItemViewModel model = null;


            if (item != null)
            {
                var buyerCurrency = _userRepository.UserCurrency(User.Identity.Name);
                var buyerCurrencyRate = _userRepository.UserCurrencyRate(User.Identity.Name);
                var sellerCurrency = _userRepository.UserCurrency(item.User.Email);
                string imgUrl = @"/images/no-image.png";

                if (item.ImgUrl != null)
                { imgUrl = item.ImgUrl; }

                if (buyerCurrency == sellerCurrency || buyerCurrency == null)
                {
                    model = new ItemViewModel()
                    {
                        ItemId = itemId,
                        ItemName = item.Name,
                        ItemDescription = item.Description,
                        SellerPrice = item.Price,
                        SellerCurrency = item.User.Country.Currency.ShortName,
                        ImgUrl = imgUrl
                    };
                }
                else
                {
                    model = new ItemViewModel()
                    {
                        ItemId = itemId,
                        ItemName = item.Name,
                        ItemDescription = item.Description,
                        SellerPrice = item.Price,
                        SellerCurrency = item.User.Country.Currency.ShortName,

                        BuyerCurrency = buyerCurrency,
                        BuyerPrice = Decimal.Round(item.Price / item.User.Country.Currency.Rate * buyerCurrencyRate, 2),
                        ImgUrl = imgUrl
                    };

                }
            }
            else
            {
                ViewBag.nullItem = "No item with such id";
                return View();
            }

            return View(model);
        }

        [Authorize]
        public IActionResult ConfirmOrder(int itemId)
        {
            var item = _repository.GetItem(itemId);
            var buyerCurrencyRate = _userRepository.UserCurrencyRate(User.Identity.Name);

            ItemOrderModel model = new ItemOrderModel();

            if (item != null)
            {
                model = new ItemOrderModel()
                {
                    ItemName = item.Name,
                    Price = item.Price * item.User.Country.Currency.Rate / buyerCurrencyRate,
                    BuyerName = User.Identity.Name,
                    ItemId = itemId,
                    SellerName = item.User.Name,
                    PossibleToShipAnotherCountry = item.IsMultiCountryPossible,
                };
            }

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Buy(ItemOrderModel model)
        {
            var item = _repository.GetItem(model.ItemId);
            var buyerCurrencyRate = _userRepository.UserCurrencyRate(User.Identity.Name);

            var buyerPrice = Decimal.Round(item.Price / item.User.Country.Currency.Rate * buyerCurrencyRate, 2);

            if (_orderRepository.PlaceOrder(model.ItemId, buyerPrice, model.BuyerName, model.Qty, model.Status))
            {
                var buyer = _userRepository.FindUserByName(model.BuyerName);
                var MessageForSeller = $"Buyer {buyer.Name} with email {buyer.Email} has purchased item {item.Name}. Please contact him";
                var MessageForBuyer = $"You have placed new order for item {item.Name} from {item.User.Name} whos email is {item.User.Email} In urgent cases you can email to seller";

                await _messageService.SendMessageAsync("email", MessageForSeller, "New order", item.User.Email); // message to seller
                await _messageService.SendMessageAsync("email", MessageForBuyer, "Order confirmation", buyer.Email); // message to buyer

                ViewBag.Status = "Order has been placed. Seller will contact you as soon as possible. Please check email";
            }
            else
            {
                ViewBag.Status = "Error";
            }

            return View();
        }


    }
}

TradingPlatform/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using TradingPlatform.Repositories;
using TradingPlatform.ViewModels;

namespace TradingPlatform.Controllers
{
    public class ItemsController : Controller
    {
        private IItemRepository _itemRepository { get; set; }

        private IWebHostEnvironment _appEnvironment { get; set; }

        private ICategoryRepository _categoryRepository { get; set; }

        public ItemsController(IItemRepository itemrepository, IWebHostEnvironment appEnvironment, ICategoryRepository categoryRepository)
        {
            _itemRepository = itemrepository;
            _appEnvironment = appEnvironment;
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Category(int categoryId)
        {
            var itemsList = _itemRepository.GetCategorisedItems(categoryId);

            if (itemsList != null && itemsList.Count() > 0)
            {
                ViewBag.ItemsList = new List<ItemListViewModel>();
                ViewBag.CategoryName = _categoryRepository.GetCategoryName(categoryId);

                foreach (var t in itemsList)
                {
                    string noImg = @"/images/no-image.png";

                    if (t.ImgUrl == null)
                    {
                        t.ImgUrl = noImg;
                    }
                    ViewBag.ItemsList.Add(new ItemListViewModel { ItemId = t.Id, ItemName = t.Name, Price = t.Price, Currency = t.User.Country.Currency.ShortName, ImgUrl = t.ImgUrl });
                }
            }

            return View();
        }

        [Authorize]
        public IActionResult MyItems()
        {
            var userName = User.Identity.Name;
            var itemsList = _itemRepository.GetUserItems(userName);
            List<ItemListViewModel> model = new List<ItemListViewModel>();

            if (User.Identity.IsAuthenticated)
            {
                if (itemsList != null && itemsList.Count() > 0)
                {
                   foreach (var item in itemsList.ToList())
                    {
                        string noImg = @"/images/no-image.png";

                        if (item.ImgUrl == null)
                        {
                            item.ImgUrl = noImg;
                        }

                        model.Add(new ItemListViewModel { ItemId = item.Id, ItemName = item.Name, Price = item.Price, Currency = item.User.Country.Currency.ShortName, ImgUrl = item.ImgUrl });
                    }
                }
                else
                {
                    model = null;
                }
            }
                

            

            return View(model);
        }
    }
}

TradingPlatform/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TradingPlatform.Repositories;
using TradingPlatform.ViewModels;

namespace TradingPlatform.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository _ordersRepository;

        private IUserRepository _usersRepository;

        public OrderController (IOrderRepository ordersRepository, IUserRepository usersRepository)
        {
            _ordersRepository = ordersRepository;
            _usersRepository = usersRepository;
        }

        [Authorize]
        public IActionResult MyOrders()
        {
            var userName = User.Identity.Name;
            ViewBag.OrdersList = new List<BuyerOrderListViewModel>();

            if (User.Identity.IsAuthenticated)
            {    
                var user = _usersRepository.FindUserByName(userName);
                var ordersList = _ordersRepository.GetUsersPurchasesList(user);
                var tempOrdersList = (user != null && ordersList != null) ? ordersList : null;
                

                if (tempOrdersList != null)
                {
                    foreach (var item in tempOrdersList)
                    {
                        ViewBag.OrdersList.Add(new BuyerOrderListViewModel() { 
                            ItemName = item.ItemName, 
                            CurrencyName = item.User.Country.Currency.ShortName, 
                            OrderDate = item.DateTime, 
                            OrderId=item.Id, 
                            Price = item.Price, 
                            SellerEmail = item.Item.User.Email,
                            SellerName = item.Item.User.Name,
                            Status = item.Status,
                            TrackingNumber = item.TrackingNumber
                        });
                    }
                }
                else
                {
                    ViewBag.OrdersList = null;
                }
            }

                return View();
        }

        //[Authorize]
        //public IActionResult CustomerOrders()
        //{
        //    var user = User.Identity.Name;
        //    var listOFBuyersPurvchased items = ;
        //    List<SellerItemsOrderListViewModel> orders = new List<SellerItemsOrderListViewModel>;

        //    if (User.Identity.IsAuthenticated)
        //    {

        //    }
        //}
    }
}

TradingPlatform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trading Platform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trading Platform</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @{ if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <span class="navbar-text">@User.Identity.Name </span>
                                </li>
                                <li class="nav-item">
                                    <form method="post" asp-controller="Account" asp-action="Logout">
                                        <button style="margin-left: 5px" type="submit" class="btn btn-outline-dark">Logout</button>
                                    </form>
                                </li>
                            }
                            else
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>

                            }
                        }
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item bg-light">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="AddItem">Add item</a>
                        </li>



                        @{ if (User.Identity.IsAuthenticated)
                            {


                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="MyItems">My items</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="MyOrders">My orders</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Customers orders</a>
                                </li>
                            }

                        }
                    </ul>



                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TradingPlatformTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>